CREATE TABLE IF NOT EXISTS  utilisateur(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100),
prenom VARCHAR(100),
email VARCHAR(255) NOT NULL UNIQUE,
motdepasse VARCHAR(255),
connections VARCHAR(255),
solde LONG
--FOREIGN KEY (id)
--REFERENCES transactions(id)
);

CREATE TABLE IF NOT EXISTS transactions(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
descriptions VARCHAR(255),
amount LONG
);

CREATE TABLE IF NOT EXISTS `connection`(
senderid INTEGER , FOREIGN KEY (senderid) REFERENCES utilisateur(id) ON DELETE RESTRICT ON UPDATE CASCADE,
recipientid INTEGER , FOREIGN KEY (recipientid) REFERENCES utilisateur(id) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (senderid, recipientid)
);

